version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: socialops
    ports: ["5433:5432"]
api:
  build: ./apps/api
  environment:
    QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/socialops
    QUARKUS_DATASOURCE_USERNAME: postgres
    QUARKUS_DATASOURCE_PASSWORD: postgres
  ports: ["8080:8080"]
  depends_on: [db]
web:
  build: ./apps/web
  environment:
    NEXT_PUBLIC_API_BASE: http://localhost:8080
  ports: ["3000:3000"]
  depends_on: [api]